---
# User variables
username: matt
sudoers_passwordless: "{{ username }}"
sudoers_passworded: []
shell: /bin/bash

# Ansible variables
ansible_user: "{{ username }}"
ansible_port: "{{ ssh_port }}"

# Network variables
lan_subnet: 192.168.178.0/24
lan_base: "{{ lan_subnet | regex_replace('.0/[0-9]{2}', '') }}"
cluster_ip: "{{ lan_base }}.100"

# K3s variables
api_port: 6443
k3s_version: v1.26.9+k3s1
k3s_server_location: /var/lib/rancher/k3s
api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
systemd_dir: /etc/systemd/system
extra_server_args: ""
extra_agent_args: ""

# Optional K3s variables
# extra_service_envs: [ 'ENV_VAR1=VALUE1', 'ENV_VAR2=VALUE2' ]
# List of locally available manifests to apply to the cluster, useful for PVCs or Traefik modifications.
# extra_manifests: [ '/path/to/manifest1.yaml', '/path/to/manifest2.yaml' ]
# config_yaml:  |
  # This is now an inner yaml file. Maintain the indentation.
  # YAML here will be placed as the content of /etc/rancher/k3s/config.yaml
  # See https://docs.k3s.io/installation/configuration#configuration-file

# SSH variables
ssh_port: 22
ssh_password_authentication: "no"
ssh_permit_root_login: "no"
ssh_usedns: "no"
ssh_permit_empty_password: "no"
ssh_challenge_response_auth: "no"
ssh_gss_api_authentication: "no"
ssh_x11_forwarding: "no"
sshd_state: started
ssh_restart_handler_state: restarted
ssh_allowed_users: []
ssh_allowed_groups: []
ssh_config_path: /etc/ssh/sshd_config
sshd_name: ssh

# Autoupdate variables
autoupdate_enabled: true
autoupdate_blacklist: []
autoupdate_reboot: "false"
autoupdate_reboot_time: "03:00"
autoupdate_mail_to: ""
autoupdate_mail_on_error: true

# Fail2ban variables
fail2ban_enabled: true
fail2ban_custom_configuration_template: jail.local.j2
