---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
  namespace: nextcloud
type: Opaque
stringData:
  nextcloud-password: "generate|16"
  nextcloud-username: nextcloud
  postgres-password: "generate|16"
  postgres-admin-password: "generate|16"
  postgresql-replication-password: "generate|16"
  postgres-username: nextcloud
