---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  destination:
    namespace: nextcloud
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: nextcloud
    repoURL: https://nextcloud.github.io/helm/
    targetRevision: 5.5.2
    helm:
      values: |
        internalDatabase:
          enabled: false
        externalDatabase:
          enabled: true
          type: "pgsql"
          host: nextcloud-postgresql
          port: 5432
          user: nextcloud
          password: null
          existingSecret:
            enabled: true
            secretName: nextcloud
            usernameKey: postgres-username
            passwordKey: postgres-password
          database: nextcloud
        postgresql:
          enabled: true
          global:
            postgresql:
              auth:
                username: nextcloud
                existingSecret: nextcloud
                secretKeys:
                  secretName: nextcloud
                  adminPasswordKey: postgres-password
                  userPasswordKey: postgres-password
                  replicationPasswordKey: postgres-replication-password
                database: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
  namespace: nextcloud
type: Opaque
stringData:
  nextcloud-password: "generate|16"
  nextcloud-username: nextcloud
  postgres-password: "generate|16"
  postgres-admin-password: "generate|16"
  postgresql-replication-password: "generate|16"
  postgres-username: nextcloud
