---
- name: Install fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Copy fail2ban custom configuration file into place
  ansible.builtin.template:
    src: "{{ fail2ban_custom_configuration_template }}"
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload fail2ban

- name: Ensure fail2ban is running and enabled on boot
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
