---
- name: Create MySQL databases
  hosts: server
  become: true

  pre_tasks:
    - name: Create dynamic variables
      ansible.builtin.set_fact:
        mysql_users:
          - name: "{{ mysql_k3s_user }}"
            host: localhost
            password: "{{ mysql_password }}"
            priv: "{{ k3s_database_name }}.*:ALL"

          - name: "{{ mysql_k3s_user }}"
            host: "{{ groups['server'][0] }}.fritz.box"
            password: "{{ mysql_password }}"
            priv: "{{ k3s_database_name }}.*:ALL"

          - name: "{{ mysql_k3s_user }}"
            host: "{{ groups['server'][1] }}.fritz.box"
            password: "{{ mysql_password }}"
            priv: "{{ k3s_database_name }}.*:ALL"
        mysql_replication_master: "{{ groups['server'][0] }}"

  roles:
    - geerlingguy.mysql
  vars_files:
    - vars.yml
