---
mysql_user_name: "{{ username }}"
mysql_user_password: "{{ password | password_hash('sha512', password_salt) }}"
mysql_user_home: "/home/{{ username }}"

mysql_datadir: /tank/mysql
mysql_replication_user:
  name: replication
  password: "{{ mysql_replication_password }}"
mysql_databases:
  - name: "{{ k3s_database_name }}"
    # state: absent