---
- name: Create manifests directory on first master
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: "0644"
  when: ansible_hostname == hostvars[groups['server'][0]]['ansible_hostname']

- name: Download vip rbac manifest to first master
  ansible.builtin.get_url:
    url: "https://kube-vip.io/manifests/rbac.yaml"
    dest: "/var/lib/rancher/k3s/server/manifests/vip-rbac.yaml"
    owner: root
    group: root
    mode: "0644"
  when: ansible_hostname == hostvars[groups['server'][0]]['ansible_hostname']

- name: Copy vip manifest to first master
  ansible.builtin.template:
    src: "vip.yml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/vip.yaml"
    owner: root
    group: root
    mode: "0644"
  when: ansible_hostname == hostvars[groups['server'][0]]['ansible_hostname']

- name: Copy config file to user home directory
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ ansible_user_dir }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user_id }}"
    mode: "u=rw,g=,o="

- name: Configure kubectl cluster to {{ endpoint_url }}
  ansible.builtin.command: >-
    k3s kubectl config set-cluster default
      --server={{ endpoint_url }}
      --kubeconfig {{ ansible_user_dir }}/.kube/config
  changed_when: true
  vars:
    endpoint_url: >-
      https://{{ cluster_vip | ansible.utils.ipwrap }}:6443
