---
- name: Configure K3s
  hosts: cluster
  become: true
  roles:
    - xanmanning.k3s
  vars_files:
    - vars.yml

- name: Deploy kube-vip
  hosts: server
  become: true
  roles:
    - kube-vip
  vars_files:
    - vars.yml
