---
# K3s variables
k3s_state: installed

k3s_use_unsupported_config: true
k3s_registration_address: "{{ cluster_vip }}"
k3s_become: true
k3s_server:
  tls-san: "{{ cluster_vip }}"
  disable:
    - servicelb
    - traefik

k3s_agent:
  kubelet-arg:
    - "node-status-update-frequency=5s"

# Kube-vip variables
kube_vip_tag_version: "v0.6.4"
kube_vip_iface: eth0
