---
- name: Ensure all necessary groups are created
  ansible.builtin.group:
    name: "{{ item }}"
  loop:
    - "{{ username }}"

- name: Ensure non-root user is created
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512', password_salt) }}"
    groups:
      - sudo
      - users
    append: true
    update_password: on_create

- name: Set authorised key
  ansible.posix.authorized_key:
    key: "{{ lookup('ansible.builtin.file', cluster_vars.ssh.authorised_key) }}"
    user: "{{ username }}"

- name: Suppress login message
  ansible.builtin.file:
    path: /home/{{ username }}/.hushlogin
    mode: "0644"
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve
    state: touch
