---
- name: Create Traefik Deployment
  kubernetes.core.k8s:
    state: present
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: traefik-deployment
        namespace: traefik
        labels:
          app: traefik

      spec:
        replicas: 1
        selector:
          matchLabels:
            app: traefik
        template:
          metadata:
            labels:
              app: traefik
          spec:
            serviceAccountName: traefik-account
            containers:
              - name: traefik
                image: traefik:v3.1
                args:
                  - --api.insecure
                  - --providers.kubernetesingress
                ports:
                  - name: web
                    containerPort: 80
                  - name: dashboard
                    containerPort: 8080
