---
- name: Configure dashboard IngressRoute
  kubernetes.core.k8s:
    state: present
    definition:
      kind: IngressRoute
      apiVersion: traefik.io/v1alpha1
      metadata:
        name: traefik-dashboard
        namespace: traefik
      spec:
        entryPoints:
          - web
          - websecure
        routes:
          - match: Host(`traefik.turing`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
            kind: Rule
            services:
              - name: api@internal
                kind: TraefikService
