---
- name: Install prerequisites
  ansible.builtin.import_tasks:
    file: prerequisites.yml

- name: Deploy resources
  ansible.builtin.import_tasks:
    file: deployment.yml

- name: Configure ingress
  ansible.builtin.import_tasks:
    file: ingress.yml
