---
- name: Create Namespace
  kubernetes.core.k8s:
    state: present
    name: traefik
    api_version: v1
    kind: Namespace

- name: Install Helm chart
  kubernetes.core.k8s:
    state: present
    definition:
      kind: HelmChart
      apiVersion: helm.cattle.io/v1
      metadata:
        name: traefik
        namespace: traefik
      spec:
        repo: https://traefik.github.io/charts
        chart: traefik
        targetNamespace: traefik
        valuesContent: |-
          ingressRoute:
            dashboard:
              enabled: true
              entryPoints: ["websecure"]
