---
- name: Create Traefik Services
  kubernetes.core.k8s:
    state: present
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: traefik-dashboard
        namespace: traefik

      spec:
        type: LoadBalancer
        ports:
          - port: 8080
            targetPort: dashboard
        selector:
          app: traefik
